# Generated by Django 4.1.7 on 2023-03-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='', upload_to='blog_photos'),
            preserve_default=False,
        ),
    ]
